language: python
python:
  - "3.6"

sudo: false

cache: pip

install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt

script:
  - py.test --cov=. flask_tinyauth
  - flake8 flask_tinyauth

after_success:
  - codecov
