
version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  nginx_tls: {}

services:
  postgres:
    image: postgres:9.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
      - POSTGRES_DB=tinyauth

  tinyauth:
    image: tinyauth/tinyauth:dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth

  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app/src

  nginx:
    build: ./docker/nginx
    volumes:
      - nginx_tls:/etc/nginx/external/
    depends_on:
      - flask
    ports:
      - "0.0.0.0:443:443"
    restart: always
