FROM python:3.6

ENV PYTHONUNBUFFERED 1

RUN groupadd -r flask && useradd -r -g flask flask

COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

WORKDIR /app/src

ENV PYTHONPATH=.
ENV FLASK_APP=/app/src/docker/flask/helloworld.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]
